import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export interface PDFExportOptions {
  filename: string;
  title?: string;
  author?: string;
  download?: boolean;
}

/**
 * Export HTML element to PDF
 */
export async function exportElementToPDF(
  element: HTMLElement,
  options: PDFExportOptions
) {
  try {
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
    });

    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const imgData = canvas.toDataURL('image/png');
    const imgWidth = pageWidth - 20;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    let yPosition = 10;

    if (options.title) {
      pdf.setFontSize(16);
      pdf.text(options.title, 10, yPosition);
      yPosition += 15;
    }

    if (options.author) {
      pdf.setFontSize(10);
      pdf.text(`Generated by: ${options.author}`, 10, yPosition);
      yPosition += 10;
    }

    // Add image, handling page breaks
    if (imgHeight > pageHeight - yPosition) {
      pdf.addImage(imgData, 'PNG', 10, yPosition, imgWidth, pageHeight - yPosition - 10);
      let remainingHeight = imgHeight - (pageHeight - yPosition - 10);

      while (remainingHeight > 0) {
        pdf.addPage();
        pdf.addImage(
          imgData,
          'PNG',
          10,
          10,
          imgWidth,
          Math.min(remainingHeight, pageHeight - 20)
        );
        remainingHeight -= pageHeight - 20;
      }
    } else {
      pdf.addImage(imgData, 'PNG', 10, yPosition, imgWidth, imgHeight);
    }

    if (options.download !== false) {
      pdf.save(options.filename);
    }

    return pdf;
  } catch (error) {
    console.error('Error exporting to PDF:', error);
    throw error;
  }
}

/**
 * Generate invoice PDF
 */
export async function generateInvoicePDF(invoiceData: {
  invoiceNumber: string;
  clientName: string;
  amount: number;
  items: Array<{ description: string; quantity: number; rate: number }>;
  dueDate: string;
  issueDate: string;
}) {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  let yPosition = 20;

  // Header
  pdf.setFontSize(24);
  pdf.text('INVOICE', pageWidth - 20, yPosition, { align: 'right' });

  // Invoice details
  yPosition += 15;
  pdf.setFontSize(10);
  pdf.text(`Invoice #: ${invoiceData.invoiceNumber}`, pageWidth - 20, yPosition, { align: 'right' });
  yPosition += 6;
  pdf.text(`Issued: ${invoiceData.issueDate}`, pageWidth - 20, yPosition, { align: 'right' });
  yPosition += 6;
  pdf.text(`Due: ${invoiceData.dueDate}`, pageWidth - 20, yPosition, { align: 'right' });

  // Client info
  yPosition += 12;
  pdf.setFontSize(12);
  pdf.text('Bill To:', 20, yPosition);
  yPosition += 8;
  pdf.setFontSize(10);
  pdf.text(invoiceData.clientName, 20, yPosition);

  // Line items table
  yPosition += 15;
  const tableStartY = yPosition;
  
  // Table header
  pdf.setDrawColor(200, 200, 200);
  pdf.rect(20, tableStartY, pageWidth - 40, 8);
  pdf.setFontSize(10);
  pdf.setTextColor(0, 0, 0);
  pdf.text('Description', 25, tableStartY + 6);
  pdf.text('Qty', 130, tableStartY + 6, { align: 'center' });
  pdf.text('Rate', 150, tableStartY + 6, { align: 'center' });
  pdf.text('Amount', 170, tableStartY + 6, { align: 'right' });

  // Table rows
  yPosition = tableStartY + 12;
  invoiceData.items.forEach((item) => {
    const amount = item.quantity * item.rate;
    pdf.text(item.description, 25, yPosition);
    pdf.text(item.quantity.toString(), 130, yPosition, { align: 'center' });
    pdf.text(`$${item.rate.toFixed(2)}`, 150, yPosition, { align: 'center' });
    pdf.text(`$${amount.toFixed(2)}`, 170, yPosition, { align: 'right' });
    yPosition += 6;
  });

  // Total
  yPosition += 5;
  pdf.setDrawColor(200, 200, 200);
  pdf.line(130, yPosition, 175, yPosition);
  yPosition += 8;
  pdf.setFontSize(12);
  pdf.setFont(undefined, 'bold');
  pdf.text(`Total: $${invoiceData.amount.toFixed(2)}`, 170, yPosition, { align: 'right' });

  return pdf;
}

/**
 * Generate profitability report PDF
 */
export async function generateProfitabilityReportPDF(reportData: {
  projectName: string;
  quotedPrice: number;
  revenue: number;
  costs: number;
  margin: number;
  costBreakdown: Record<string, number>;
}) {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  let yPosition = 20;

  // Title
  pdf.setFontSize(20);
  pdf.text('Profitability Report', 20, yPosition);
  yPosition += 10;

  pdf.setFontSize(12);
  pdf.text(reportData.projectName, 20, yPosition);
  yPosition += 15;

  // Key metrics
  pdf.setFontSize(11);
  pdf.text(`Quoted Price: $${reportData.quotedPrice.toFixed(2)}`, 20, yPosition);
  yPosition += 8;
  pdf.text(`Revenue: $${reportData.revenue.toFixed(2)}`, 20, yPosition);
  yPosition += 8;
  pdf.text(`Total Costs: $${reportData.costs.toFixed(2)}`, 20, yPosition);
  yPosition += 8;
  pdf.setFont(undefined, 'bold');
  pdf.text(`Profit Margin: ${reportData.margin.toFixed(1)}%`, 20, yPosition);
  pdf.setFont(undefined, 'normal');

  // Cost breakdown
  yPosition += 15;
  pdf.setFontSize(12);
  pdf.text('Cost Breakdown', 20, yPosition);
  yPosition += 8;

  pdf.setFontSize(10);
  Object.entries(reportData.costBreakdown).forEach(([category, cost]) => {
    const percentage = ((cost / reportData.costs) * 100).toFixed(1);
    pdf.text(`${category}: $${cost.toFixed(2)} (${percentage}%)`, 20, yPosition);
    yPosition += 6;
  });

  return pdf;
}

/**
 * Generate time report PDF
 */
export async function generateTimeReportPDF(reportData: {
  projectName: string;
  startDate: string;
  endDate: string;
  entries: Array<{
    date: string;
    description: string;
    hours: number;
    hourlyRate: number;
  }>;
  totalHours: number;
  totalCost: number;
}) {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  let yPosition = 20;

  // Title
  pdf.setFontSize(18);
  pdf.text('Time Report', 20, yPosition);
  yPosition += 12;

  // Project info
  pdf.setFontSize(10);
  pdf.text(`Project: ${reportData.projectName}`, 20, yPosition);
  yPosition += 6;
  pdf.text(`Period: ${reportData.startDate} to ${reportData.endDate}`, 20, yPosition);
  yPosition += 12;

  // Table header
  pdf.setDrawColor(200, 200, 200);
  pdf.rect(20, yPosition, pageWidth - 40, 8);
  pdf.setFontSize(10);
  pdf.text('Date', 25, yPosition + 6);
  pdf.text('Description', 50, yPosition + 6);
  pdf.text('Hours', 130, yPosition + 6, { align: 'center' });
  pdf.text('Rate', 150, yPosition + 6, { align: 'center' });
  pdf.text('Total', 170, yPosition + 6, { align: 'right' });

  yPosition += 12;

  // Table rows
  reportData.entries.forEach((entry) => {
    const total = entry.hours * entry.hourlyRate;
    pdf.text(entry.date, 25, yPosition);
    pdf.text(entry.description, 50, yPosition);
    pdf.text(entry.hours.toString(), 130, yPosition, { align: 'center' });
    pdf.text(`$${entry.hourlyRate.toFixed(2)}`, 150, yPosition, { align: 'center' });
    pdf.text(`$${total.toFixed(2)}`, 170, yPosition, { align: 'right' });
    yPosition += 6;
  });

  // Summary
  yPosition += 8;
  pdf.setDrawColor(200, 200, 200);
  pdf.line(130, yPosition, 175, yPosition);
  yPosition += 8;

  pdf.setFont(undefined, 'bold');
  pdf.text(`Total Hours: ${reportData.totalHours}`, 20, yPosition);
  yPosition += 8;
  pdf.text(`Total Cost: $${reportData.totalCost.toFixed(2)}`, 170, yPosition, { align: 'right' });

  return pdf;
}

/**
 * Batch export multiple PDFs
 */
export async function exportMultiplePDFs(
  items: Array<{ element: HTMLElement; filename: string }>,
  zipFileName: string
) {
  // Note: This would require a zip library. For now, downloads individually.
  for (const item of items) {
    await exportElementToPDF(item.element, { filename: item.filename });
    // Add delay to prevent browser blocking
    await new Promise(resolve => setTimeout(resolve, 500));
  }
}
